spring.application.name=buildings
spring.main.headless=false

buildings.input.balans=data/input/Баланс.xlsx
buildings.input.free-space=data/input/ВільніПлощі.xlsx
buildings.input.orenda=data/input/Оренда.xlsx
buildings.output.buildings=data/output/buildings.csv
buildings.output.buildings-rentable=data/output/buildingsRentable.csv
buildings.output.prozorro-buildings-rentable=data/output/listProzorroSales_buildingsRentable.csv
buildings.output.list=data/output/list.csv
buildings.output.prozorro-list=data/output/listProzorroSales_rented.csv

#logging.config=classpath:logback-spring.xml2
logging.level.root=info
logging.file.name=logs/buildings.log
logging.file.path=logs
#logging.pattern.console=%clr([%-5level]){faint} - %msg%n
#logging.pattern.file=[%-5level] - %msg%n
