spring.application.name=buildings

#logging.config=classpath:logback-spring.xml2
logging.level.root=info
logging.file.name=logs/buildings.log
logging.file.path=logs
#logging.pattern.console=%clr([%-5level]){faint} - %msg%n
#logging.pattern.file=[%-5level] - %msg%n
