package com.vva.buildings

enum class BuildingIndex(val index: Int) {
    id(0),
    isPartOf(1),
    title(2),
    kind(3),
    type(4),
    description(5),
    ownerName(6),
    ownerId(7),
    balanceHolderName(8),
    balanceHolderId(9),
    userName(10),
    userId(11),
    dk018classId(12),
    dk018classDescription(13),
    unitName(14),
    area(15),
    CATUTTC(16),
    addressPostCode(17),
    addressAdminUnitL1(18),
    addressAdminUnitL2(19),
    addressAdminUnitL3(20),
    addressAdminUnitL4(21),
    addressPostName(22),
    addressPostDistrict(23),
    addressPostStreet(24),
    addressLocatorDesignator(25),
    addressLocatorBuilding(26),
    addressLocatorName(27),
    registrationStatus(28),
    registrationId(29),
    registrationDate(30),
    constructionReadiness(31),
    condition(32),
    utilitiesAvailable(33),
    validityDate(34),
    destinationGroup(35) // Група призначення
}